version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    command: --secure-file-priv='/var/lib/mysql-files'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql
      - /Users/amiraliazim/Desktop/3B/ECE356/project/Networking_dataset:/var/lib/mysql-files/
volumes:
  my-db: